### ISSUE TITLE
Path object has no attribute listdir

### ISSUE THREAD

**Issue by TheRainstorm** [jiandandaoxingfu/pdfdo#1]
Environments:

- Python 3.10.12
- package `path` 17.0.0

```shell
➜  pdf-cut-white git:(master) ✗ python cli.py -id /mnt/Disk1/Workspace/images -od /mnt/Disk1/Workspace/images_pdf_cut --ignore 1
2024-11-30 21:50:31.680 | INFO     | pdf_white_cut.worker:batch_cut_pdf:144 - input dir: /mnt/Disk1/Workspace/images
2024-11-30 21:50:31.680 | INFO     | pdf_white_cut.worker:batch_cut_pdf:145 - output dir: /mnt/Disk1/Workspace/images_pdf_cut
2024-11-30 21:50:31.680 | ERROR    | __main__:<module>:22 - 'Path' object has no attribute 'listdir'
Traceback (most recent call last):

> File "/home/yfy/app/pdf-cut-white/cli.py", line 18, in <module>
    batch_cut_pdf(args.indir, args.outdir, args.ignore)
    │             │    │      │    │       │    └ 1
    │             │    │      │    │       └ Namespace(input='', output='output.pdf', indir='/mnt/Disk1/Workspace/images', outdir='/mnt/Disk1/Workspace/images_pdf_cut', t...
    │             │    │      │    └ '/mnt/Disk1/Workspace/images_pdf_cut'
    │             │    │      └ Namespace(input='', output='output.pdf', indir='/mnt/Disk1/Workspace/images', outdir='/mnt/Disk1/Workspace/images_pdf_cut', t...
    │             │    └ '/mnt/Disk1/Workspace/images'
    │             └ Namespace(input='', output='output.pdf', indir='/mnt/Disk1/Workspace/images', outdir='/mnt/Disk1/Workspace/images_pdf_cut', t...
    └ <function batch_cut_pdf at 0x7c582dbbfb50>

  File "/home/yfy/app/pdf-cut-white/pdf_white_cut/worker.py", line 148, in batch_cut_pdf
    files = [pdf.basename() for pdf in indir.listdir("*.pdf")]
                                       └ Path('/mnt/Disk1/Workspace/images')

AttributeError: 'Path' object has no attribute 'listdir'. Did you mean: 'is_dir'?
```

Have make a pull request to fix this problem.

**Comment by TheRainstorm** [comment]
Sorry, I post in a wrong repo
